---
## Deploy a lighttpd cluster node
## I need a user account which is able to sudo without password

- hosts: nodes
  sudo: True
  user: remy

  vars:
    sshport: "22"
    pbname: $inventory_hostname


  tasks:

  - name: Check that the server is alive
    action: ping

  - name: install python-apt for debian
    action: command /usr/bin/apt-get -y install python-apt


  - name: Install packages
    action: apt name=$item state=latest
    with_items:
     - nano
     - git-core
     - mc
     - logwatch
     - links2
     - openssh-server
     - rsync
     - wget
     - htop
     - ncdu


  - name: Add dotdeb repo
    action: template src=config/dotdeb.in dest=/etc/apt/sources.list.d/dotdeb.list

  - name: Copy gpg key
    action: template src=config/dotdeb.gpg.in dest=/tmp/dotdeb.gpg

  - name: Add dotdeb gpg key
    action: command apt-key add /tmp/dotdeb.gpg 

  - name: set /etc/issue
    action: template src=config/issue.net.in dest=/etc/issue

  - name: set /etc/issue.net
    action: template src=config/issue.net.in dest=/etc/issue.net

   - name: add web deploy key
    action: authorized_key user=remy key=""

  - name: Set openssh config
    action: template src=config/sshd_config.in dest=/etc/ssh/sshd_config
    notify: restart openssh

  - name: Add mail alias
    action: 'lineinfile name=/etc/aliases regexp="^root: mail@mail.com" line="root: mail@mail.com"'
    notify: newaliases

  - name: Install custom bashrc
    action: template src=config/bashrc.in dest=/home/remy/.bashrc

  - name: Set permissions on bashrc
    action: file path=/home/remy/.bashrc state=file owner=remy group=remy mode=755  

  - name: Set up ray-mon status client script
    action: copy src=config/client.sh dest=/var/www/client.sh owner=root group=root mode=0755
    notify: raymon client

  - name: Set up cronjob every 5 minutes for the client status script
    action: template src=config/raymonclient.in dest=/etc/cron.d/raymon-client mode=0755 owner=root group=root
    notify: notify crontab of new jobs

  handlers:
    - name: restart openssh
      action: service name=ssh state=restarted

    - name: newaliases
      action: command newaliases

    - name: raymon client
      action: 'command bash /var/www/client.sh > /var/www/stat.json'

    - name: notify crontab of new jobs
      action: command sudo crontab /etc/cron.d/*